<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #f3f4f6; color: #1f2937; margin: 0; padding: 0; }
    .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; margin-top: 20px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05); }
    .header { background-color: #1f2937; color: #ffffff; padding: 24px; text-align: center; }
    .header h1 { margin: 0; font-size: 20px; font-weight: 600; }
    .content { padding: 32px; }
    .alert-badge { display: inline-block; padding: 4px 12px; border-radius: 9999px; font-size: 12px; font-weight: 600; text-transform: uppercase; background-color: #fee2e2; color: #991b1b; margin-bottom: 16px; }
    .message { font-size: 16px; line-height: 1.5; margin-bottom: 24px; color: #374151; }
    .section { background-color: #f9fafb; border: 1px solid #e5e7eb; border-radius: 6px; padding: 16px; margin-bottom: 20px; }
    .section-title { font-size: 12px; font-weight: 600; text-transform: uppercase; color: #6b7280; margin-bottom: 8px; letter-spacing: 0.05em; }
    .code-block { font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace; font-size: 12px; background-color: #1e293b; color: #e2e8f0; padding: 12px; border-radius: 4px; overflow-x: auto; white-space: pre-wrap; word-break: break-all; }
    .stat-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 16px; margin-bottom: 20px; }
    .stat-item { background-color: #f9fafb; border: 1px solid #e5e7eb; border-radius: 6px; padding: 12px; }
    .stat-label { font-size: 11px; text-transform: uppercase; color: #6b7280; font-weight: 600; margin-bottom: 4px; }
    .stat-value { font-size: 14px; font-weight: 600; color: #111827; }
    .footer { background-color: #f9fafb; padding: 24px; text-align: center; border-top: 1px solid #e5e7eb; font-size: 12px; color: #6b7280; }
    .btn { display: inline-block; background-color: #4f46e5; color: #ffffff; padding: 10px 20px; border-radius: 6px; text-decoration: none; font-weight: 500; font-size: 14px; margin-top: 8px; }
    .text-red { color: #dc2626; }
    .text-green { color: #059669; }
</style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Query Analyzer Alert</h1>
        </div>
        <div class="content">
            <span class="alert-badge">{{ $alert->type }}</span>
            <div class="message">{{ $messageContent }}</div>

            <div class="stat-grid">
                <div class="stat-item">
                    <div class="stat-label">Execution Time</div>
                    <div class="stat-value {{ ($context['time'] ?? 0) > 1.0 ? 'text-red' : '' }}">{{ number_format($context['time'] ?? 0, 4) }}s</div>
                </div>
                <div class="stat-item">
                    <div class="stat-label">Connection</div>
                    <div class="stat-value">{{ $context['connection'] ?? 'default' }}</div>
                </div>
            </div>

            @if(isset($context['sql']))
            <div class="section">
                <div class="section-title">SQL Statement</div>
                <div class="code-block">{{ $context['sql'] }}</div>
            </div>
            @endif

            @if(isset($context['origin']['file']))
            <div class="section">
                <div class="section-title">Origin</div>
                <div style="font-size: 12px; word-break: break-all; color: #4b5563;">
                    <strong>File:</strong> {{ $context['origin']['file'] }}<br>
                    <strong>Line:</strong> {{ $context['origin']['line'] }}
                </div>
            </div>
            @endif

            @if(!empty($context['issues']))
            <div class="section">
                <div class="section-title">Detected Issues</div>
                <ul style="margin: 0; padding-left: 20px; font-size: 13px; color: #b91c1c;">
                    @foreach($context['issues'] as $issue)
                        <li>{{ $issue['message'] ?? $issue }}</li>
                    @endforeach
                </ul>
            </div>
            @endif

            <div style="text-align: center;">
                <a href="{{ route('query-lens.dashboard') }}" class="btn">View Dashboard</a>
            </div>
        </div>
        <div class="footer">
            Generated by Laravel Query Analyzer
        </div>
    </div>
</body>
</html>
